// <auto-generated />
using System;
using DoctorFactory.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoctorFactory.SqlServer.Migrations
{
    [DbContext(typeof(RezidentDatabase))]
    [Migration("20231210203105_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("EntitySequence");

            modelBuilder.Entity("BlogPostTag", b =>
                {
                    b.Property<int>("PostsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("PostsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("BlogPostTag");
                });

            modelBuilder.Entity("CourseInstructor", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.Property<int>("InstructorsId")
                        .HasColumnType("int");

                    b.HasKey("CoursesId", "InstructorsId");

                    b.HasIndex("InstructorsId");

                    b.ToTable("CourseInstructor");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Base.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [EntitySequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Base.Flashcard", b =>
                {
                    b.HasBaseType("DoctorFactory.Domain.Entities.Base.Entity");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CourseCategoryId");

                    b.HasIndex("LessonId");

                    b.ToTable("Flashcard");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Blog.Author", b =>
                {
                    b.HasBaseType("DoctorFactory.Domain.Entities.Base.Entity");

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocupation")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Blog.BlogCategory", b =>
                {
                    b.HasBaseType("DoctorFactory.Domain.Entities.Base.Entity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.HasIndex("ParentId");

                    b.ToTable("BlogCategories");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Blog.BlogPost", b =>
                {
                    b.HasBaseType("DoctorFactory.Domain.Entities.Base.Entity");

                    b.Property<int>("BlogPostAuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateUpdate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MainImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("BlogPostAuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Blog.BlogReview", b =>
                {
                    b.HasBaseType("DoctorFactory.Domain.Entities.Base.Entity");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.HasIndex("PostId");

                    b.ToTable("BlogReviews");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Blog.Tag", b =>
                {
                    b.HasBaseType("DoctorFactory.Domain.Entities.Base.Entity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.Course", b =>
                {
                    b.HasBaseType("DoctorFactory.Domain.Entities.Base.Entity");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateCreation")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateUpdate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Enrolled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentationVideo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SkillLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.CourseCategory", b =>
                {
                    b.HasBaseType("DoctorFactory.Domain.Entities.Base.Entity");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasIndex("ParentId");

                    b.ToTable("CourseCategories");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.CourseGoal", b =>
                {
                    b.HasBaseType("DoctorFactory.Domain.Entities.Base.Entity");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseGoals");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.CourseRequirement", b =>
                {
                    b.HasBaseType("DoctorFactory.Domain.Entities.Base.Entity");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseRequirements");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.CourseReview", b =>
                {
                    b.HasBaseType("DoctorFactory.Domain.Entities.Base.Entity");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseReviews");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.Instructor", b =>
                {
                    b.HasBaseType("DoctorFactory.Domain.Entities.Base.Entity");

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocupation")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.Lesson", b =>
                {
                    b.HasBaseType("DoctorFactory.Domain.Entities.Base.Entity");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<bool>("IsAvaible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.LessonContent", b =>
                {
                    b.HasBaseType("DoctorFactory.Domain.Entities.Base.Entity");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Video")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonContents");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.Quiz", b =>
                {
                    b.HasBaseType("DoctorFactory.Domain.Entities.Base.Entity");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("LessonId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.QuizAnswer", b =>
                {
                    b.HasBaseType("DoctorFactory.Domain.Entities.Base.Entity");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRight")
                        .HasColumnType("bit");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizAnswer");
                });

            modelBuilder.Entity("BlogPostTag", b =>
                {
                    b.HasOne("DoctorFactory.Domain.Entities.Blog.BlogPost", null)
                        .WithMany()
                        .HasForeignKey("PostsId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("DoctorFactory.Domain.Entities.Blog.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseInstructor", b =>
                {
                    b.HasOne("DoctorFactory.Domain.Entities.Course.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("DoctorFactory.Domain.Entities.Course.Instructor", null)
                        .WithMany()
                        .HasForeignKey("InstructorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Base.Flashcard", b =>
                {
                    b.HasOne("DoctorFactory.Domain.Entities.Course.CourseCategory", "CourseCategory")
                        .WithMany()
                        .HasForeignKey("CourseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoctorFactory.Domain.Entities.Course.Lesson", "Lesson")
                        .WithMany("Flashcards")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CourseCategory");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Blog.BlogCategory", b =>
                {
                    b.HasOne("DoctorFactory.Domain.Entities.Blog.BlogCategory", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Blog.BlogPost", b =>
                {
                    b.HasOne("DoctorFactory.Domain.Entities.Blog.Author", "BlogPostAuthor")
                        .WithMany("Posts")
                        .HasForeignKey("BlogPostAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoctorFactory.Domain.Entities.Blog.BlogCategory", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPostAuthor");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Blog.BlogReview", b =>
                {
                    b.HasOne("DoctorFactory.Domain.Entities.Blog.BlogPost", "Post")
                        .WithMany("Reviews")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.Course", b =>
                {
                    b.HasOne("DoctorFactory.Domain.Entities.Course.CourseCategory", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.CourseCategory", b =>
                {
                    b.HasOne("DoctorFactory.Domain.Entities.Course.CourseCategory", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.CourseGoal", b =>
                {
                    b.HasOne("DoctorFactory.Domain.Entities.Course.Course", "Course")
                        .WithMany("Goals")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.CourseRequirement", b =>
                {
                    b.HasOne("DoctorFactory.Domain.Entities.Course.Course", "Course")
                        .WithMany("Requirements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.CourseReview", b =>
                {
                    b.HasOne("DoctorFactory.Domain.Entities.Course.Course", "Course")
                        .WithMany("Reviews")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.Lesson", b =>
                {
                    b.HasOne("DoctorFactory.Domain.Entities.Course.Course", "Course")
                        .WithMany("Content")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.LessonContent", b =>
                {
                    b.HasOne("DoctorFactory.Domain.Entities.Course.Lesson", "Lesson")
                        .WithMany("Content")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.Quiz", b =>
                {
                    b.HasOne("DoctorFactory.Domain.Entities.Course.Lesson", "Lesson")
                        .WithMany("Quizzes")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.QuizAnswer", b =>
                {
                    b.HasOne("DoctorFactory.Domain.Entities.Course.Quiz", "Quiz")
                        .WithMany("Answers")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Blog.Author", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Blog.BlogCategory", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Blog.BlogPost", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.Course", b =>
                {
                    b.Navigation("Content");

                    b.Navigation("Goals");

                    b.Navigation("Requirements");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.CourseCategory", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.Lesson", b =>
                {
                    b.Navigation("Content");

                    b.Navigation("Flashcards");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("DoctorFactory.Domain.Entities.Course.Quiz", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
